moving to terraform p1

diff --git a/.github/workflows/yolo5-deployment.yaml b/.github/workflows/yolo5-deployment.yaml
--- a/.github/workflows/yolo5-deployment.yaml
+++ b/.github/workflows/yolo5-deployment.yaml
@@ -36,103 +36,103 @@ jobs:
           docker push 019273956931.dkr.ecr.eu-central-1.amazonaws.com/$IMAGE_NAME
           echo "image_ver=$IMAGE_VER" >> "$GITHUB_OUTPUT"
 
-  Deploy:
-    runs-on: ubuntu-latest
-    env:
-      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      IMAGE_VER: ${{ needs.Build.outputs.image_ver }}
-    needs:
-      - Build
-
-    steps:
-      - name: Checkout the repo code
-        uses: actions/checkout@v4
-
-      - name: Deploy new version
-        id: set_ip
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          IMAGE_VER: ${{ needs.Build.outputs.image_ver }}
-        run: |
-          tag_key="App"
-          tag_value="yolo5"
-          
-          # AWS CLI command to describe instances with the specified tag
-          instance_info=$(aws ec2 describe-instances --region "eu-central-1"\
-            --query 'Reservations[*].Instances[*].{InstanceId:InstanceId}' \
-            --filters "Name=tag:App,Values=yolo5" "Name=instance-state-name,Values=running" \
-            --output text)
-          
-          # Output the the tag:
-          echo "the tag key is: $tag_key and the value is: $tag_value"
-          
-          echo "
-            ----
-          $instance_info
-            ----
-          "
-          # echo "instance_info=\"${instance_info}\"" >> "$GITHUB_ENV"
-          
-          # Check if instance_info is not empty
-          if [ -n "$instance_info" ]; then
-            # Extract instance IDs from JSON
-            instance_ids=$instance_info
-
-          else
-            echo "No instances found with tag ${tag_key}=${tag_value}"
-            echo $IPS
-            exit 1
-          fi
-          # Iterate through each instance ID
-          # instance_ids=${{ steps.validate_inst.outputs.instance_ids }}
-          for instance_id in $instance_ids; do
-        
-            # Check if instance is running
-            state=$(aws ec2 describe-instances --region "eu-central-1" \
-              --query 'Reservations[*].Instances[*].{State:State.Name}' \
-              --filters "Name=instance-id,Values=$instance_id" \
-              --output text)
-    
-            echo "Instance ID: $instance_id"
-            echo "Current State: $state"
-    
-            if [ "$state" != "running" ] && [ "$state" != "terminated" ]; then
-              echo "Starting instance..."
-              aws ec2 start-instances --region "eu-central-1" --instance-ids $instance_id
-  
-              # Wait until the instance is running
-              aws ec2 wait instance-running --region "eu-central-1" --instance-ids $instance_id
-  
-              # Retrieve updated information after starting
-            fi
-          done
-
-          public_ips=$(aws ec2 describe-instances --region "eu-central-1" \
-            --query 'Reservations[*].Instances[*].{PublicIpAddress:PublicIpAddress}' \
-            --filters "Name=tag:App,Values=yolo5" "Name=instance-state-name,Values=running" \
-            --output text)
-          echo $public_ips
-          
-          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" >> tempkey.pem
-          chmod 400 "tempkey.pem"
-          IMAGEVER=$IMAGE_VER
-          echo $public_ips
-          
-          IFS=$'\n'
-          for IP in $public_ips; do
-            echo "first of loop"
-            ssh -i tempkey.pem -o StrictHostKeyChecking=no "ubuntu@$IP" "
-              aws ecr get-login-password \
-                --region ${{ env.REGION }} | sudo -u ubuntu docker login --username AWS \
-                --password-stdin 019273956931.dkr.ecr.eu-central-1.amazonaws.com;
-              
-              echo "second part"  
-              docker stop $(docker ps -q -a);
-              docker stop yolo5;
-              docker container prune -f;
-              docker run --restart on-failure \
-                --name yolo5 -d -p 8443:8443 \
-                019273956931.dkr.ecr.eu-central-1.amazonaws.com/aws-project-yolo5:$IMAGEVER;"
-          done
+#  Deploy:
+#    runs-on: ubuntu-latest
+#    env:
+#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#      IMAGE_VER: ${{ needs.Build.outputs.image_ver }}
+#    needs:
+#      - Build
+#
+#    steps:
+#      - name: Checkout the repo code
+#        uses: actions/checkout@v4
+#
+#      - name: Deploy new version
+#        id: set_ip
+#        env:
+#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#          IMAGE_VER: ${{ needs.Build.outputs.image_ver }}
+#        run: |
+#          tag_key="App"
+#          tag_value="yolo5"
+#
+#          # AWS CLI command to describe instances with the specified tag
+#          instance_info=$(aws ec2 describe-instances --region "eu-central-1"\
+#            --query 'Reservations[*].Instances[*].{InstanceId:InstanceId}' \
+#            --filters "Name=tag:App,Values=yolo5" "Name=instance-state-name,Values=running" \
+#            --output text)
+#
+#          # Output the the tag:
+#          echo "the tag key is: $tag_key and the value is: $tag_value"
+#
+#          echo "
+#            ----
+#          $instance_info
+#            ----
+#          "
+#          # echo "instance_info=\"${instance_info}\"" >> "$GITHUB_ENV"
+#
+#          # Check if instance_info is not empty
+#          if [ -n "$instance_info" ]; then
+#            # Extract instance IDs from JSON
+#            instance_ids=$instance_info
+#
+#          else
+#            echo "No instances found with tag ${tag_key}=${tag_value}"
+#            echo $IPS
+#            exit 1
+#          fi
+#          # Iterate through each instance ID
+#          # instance_ids=${{ steps.validate_inst.outputs.instance_ids }}
+#          for instance_id in $instance_ids; do
+#
+#            # Check if instance is running
+#            state=$(aws ec2 describe-instances --region "eu-central-1" \
+#              --query 'Reservations[*].Instances[*].{State:State.Name}' \
+#              --filters "Name=instance-id,Values=$instance_id" \
+#              --output text)
+#
+#            echo "Instance ID: $instance_id"
+#            echo "Current State: $state"
+#
+#            if [ "$state" != "running" ] && [ "$state" != "terminated" ]; then
+#              echo "Starting instance..."
+#              aws ec2 start-instances --region "eu-central-1" --instance-ids $instance_id
+#
+#              # Wait until the instance is running
+#              aws ec2 wait instance-running --region "eu-central-1" --instance-ids $instance_id
+#
+#              # Retrieve updated information after starting
+#            fi
+#          done
+#
+#          public_ips=$(aws ec2 describe-instances --region "eu-central-1" \
+#            --query 'Reservations[*].Instances[*].{PublicIpAddress:PublicIpAddress}' \
+#            --filters "Name=tag:App,Values=yolo5" "Name=instance-state-name,Values=running" \
+#            --output text)
+#          echo $public_ips
+#
+#          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" >> tempkey.pem
+#          chmod 400 "tempkey.pem"
+#          IMAGEVER=$IMAGE_VER
+#          echo $public_ips
+#
+#          IFS=$'\n'
+#          for IP in $public_ips; do
+#            echo "first of loop"
+#            ssh -i tempkey.pem -o StrictHostKeyChecking=no "ubuntu@$IP" "
+#              aws ecr get-login-password \
+#                --region ${{ env.REGION }} | sudo -u ubuntu docker login --username AWS \
+#                --password-stdin 019273956931.dkr.ecr.eu-central-1.amazonaws.com;
+#
+#              echo "second part"
+#              docker stop $(docker ps -q -a);
+#              docker stop yolo5;
+#              docker container prune -f;
+#              docker run --restart on-failure \
+#                --name yolo5 -d -p 8443:8443 \
+#                019273956931.dkr.ecr.eu-central-1.amazonaws.com/aws-project-yolo5:$IMAGEVER;"
+#          done
